#!/bin/bash
# Cortex AI Agent Acceleration Config
# Add these to your shell profile (~/.zshrc, ~/.bashrc, or ~/.config/fish/config.fish)
#
# Generated by: /scaffold-toolbox configure
# Documentation: https://medium.com/@karkeralathesh/the-hidden-cli-tools-that-make-ai-coding-agents-10x-faster

# ---------------------------------------------------------------------------
# Claude Code Optimizations
# ---------------------------------------------------------------------------

# Use system ripgrep instead of Claude Code's bundled Node.js wrapper
# Effect: 2-5x faster code search on large codebases
# Requires: ripgrep installed (brew install ripgrep)
export USE_BUILTIN_RIPGREP=0
