#!/bin/bash
# Cortex AI Agent Acceleration Config
# Add these to your shell profile (~/.zshrc, ~/.bashrc, or ~/.config/fish/config.fish)
#
# Generated by: /scaffold-toolbox configure
# Documentation: https://medium.com/@karkeralathesh/the-hidden-cli-tools-that-make-ai-coding-agents-10x-faster
#
# This template auto-detects your shell and outputs the correct syntax.
# Usage:
#   source <(bash ai-agent-config.sh)        # apply to current session
#   bash ai-agent-config.sh >> ~/.zshrc       # persist permanently

# ---------------------------------------------------------------------------
# Shell detection
# ---------------------------------------------------------------------------

CURRENT_SHELL="$(basename "${SHELL:-/bin/bash}")"

is_fish() { [ "$CURRENT_SHELL" = "fish" ]; }

# Helper: emit an export line in the right syntax
emit_export() {
  local var="$1" val="$2"
  if is_fish; then
    printf 'set -gx %s %s\n' "$var" "$val"
  else
    printf 'export %s=%s\n' "$var" "$val"
  fi
}

# Helper: emit a comment
emit_comment() {
  printf '# %s\n' "$1"
}

# Helper: emit a PATH addition
emit_path_add() {
  local dir="$1"
  if is_fish; then
    printf 'fish_add_path %s\n' "$dir"
  else
    printf 'export PATH="%s:$PATH"\n' "$dir"
  fi
}

echo ""
emit_comment "==========================================================================="
emit_comment "Cortex AI Agent Acceleration Config"
emit_comment "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
emit_comment "Shell: $CURRENT_SHELL"
emit_comment "==========================================================================="

# ---------------------------------------------------------------------------
# Claude Code Optimizations
# ---------------------------------------------------------------------------

echo ""
emit_comment "--- Claude Code ---"
echo ""

emit_comment "Use system ripgrep instead of Claude Code's bundled Node.js wrapper."
emit_comment "Effect: 2-5x faster code search on large codebases."
emit_comment "Requires: ripgrep installed (brew install ripgrep)."
emit_comment "Set to 1 to revert to bundled ripgrep."
emit_export "USE_BUILTIN_RIPGREP" "0"
echo ""

emit_comment "Maximum output tokens per Claude Code response."
emit_comment "Higher values allow longer code generation; lower values save cost."
emit_comment "Default: 16384. Range: 1024-32768."
emit_export "CLAUDE_CODE_MAX_OUTPUT_TOKENS" "16384"
echo ""

emit_comment "Disable telemetry if preferred (set to 1 to disable)."
emit_comment "Does not affect functionality — only anonymous usage reporting."
emit_export "CLAUDE_CODE_DISABLE_TELEMETRY" "0"
echo ""

emit_comment "Max turns for subagents before they must return a result."
emit_comment "Prevents runaway subagent loops. Default: 30."
emit_export "CLAUDE_CODE_MAX_TURNS" "30"

# ---------------------------------------------------------------------------
# Codex (OpenAI) Optimizations
# ---------------------------------------------------------------------------

echo ""
emit_comment "--- Codex CLI ---"
echo ""

emit_comment "Allow Codex sandbox to make network requests."
emit_comment "Required for: npm install, pip install, API calls during tasks."
emit_comment "Set to 'false' for air-gapped environments."
emit_export "CODEX_SANDBOX_NETWORKING" "true"
echo ""

emit_comment "Codex trust mode: 'ask' (default), 'auto-edit', 'full-auto'."
emit_comment "'ask' = prompt before file writes. 'auto-edit' = auto-approve edits."
emit_comment "'full-auto' = no prompts (use with caution in production repos)."
emit_comment "Hint: start with 'ask' and promote to 'auto-edit' for trusted repos."
emit_export "CODEX_TRUST_MODE" "ask"
echo ""

emit_comment "Model selection for Codex. Options: o4-mini (default), o3, gpt-4.1."
emit_export "CODEX_DEFAULT_MODEL" "o4-mini"

# ---------------------------------------------------------------------------
# Cursor Recommendations
# ---------------------------------------------------------------------------

echo ""
emit_comment "--- Cursor IDE ---"
echo ""
emit_comment "Cursor settings are configured in the IDE, not via env vars."
emit_comment "Recommended VS Code extensions for Cursor:"
emit_comment "  - dbaeumer.vscode-eslint          (JS/TS linting)"
emit_comment "  - esbenp.prettier-vscode           (formatting)"
emit_comment "  - ms-python.python                 (Python support)"
emit_comment "  - bradlc.vscode-tailwindcss        (Tailwind CSS IntelliSense)"
emit_comment "  - prisma.prisma                    (Prisma ORM support)"
emit_comment ""
emit_comment "Recommended Cursor settings (~/.cursor/settings.json):"
emit_comment '  "editor.formatOnSave": true'
emit_comment '  "editor.defaultFormatter": "esbenp.prettier-vscode"'
emit_comment '  "cursor.aiProvider": "anthropic"    -- use Claude as Cursor backend'
emit_comment '  "cursor.chat.model": "claude-sonnet-4-20250514"'
emit_comment ""
emit_comment "For .cursorrules, run: /scaffold <repo> to generate project-specific rules."

# ---------------------------------------------------------------------------
# General: PATH additions for common tool locations
# ---------------------------------------------------------------------------

echo ""
emit_comment "--- PATH additions for installed tools ---"
echo ""

emit_comment "Homebrew (Apple Silicon default prefix)"
if [ -d "/opt/homebrew/bin" ]; then
  emit_path_add "/opt/homebrew/bin"
fi

emit_comment "Cargo (Rust tools: ripgrep, fd, bat, etc.)"
if [ -d "$HOME/.cargo/bin" ]; then
  emit_path_add "$HOME/.cargo/bin"
fi

emit_comment "Go binaries (golangci-lint, staticcheck, etc.)"
if [ -d "$HOME/go/bin" ]; then
  emit_path_add "$HOME/go/bin"
fi

emit_comment "pipx binaries (ruff, black, mypy, etc.)"
if [ -d "$HOME/.local/bin" ]; then
  emit_path_add "$HOME/.local/bin"
fi

# ---------------------------------------------------------------------------
# General: EDITOR config
# ---------------------------------------------------------------------------

echo ""
emit_comment "--- Editor config ---"
echo ""

emit_comment "Default editor for git commits, crontab, etc."
emit_comment "Common choices: vim, nvim, nano, code --wait, cursor --wait"
if command -v nvim >/dev/null 2>&1; then
  emit_export "EDITOR" "nvim"
elif command -v vim >/dev/null 2>&1; then
  emit_export "EDITOR" "vim"
else
  emit_export "EDITOR" "nano"
fi

echo ""
emit_comment "==========================================================================="
emit_comment "End of Cortex AI Agent Config"
emit_comment "==========================================================================="
